### ISSUE TITLE
Transaction name

### ISSUE THREAD

**Issue by sbcgua** [abapGit/build#10]
![image](https://user-images.githubusercontent.com/15635498/205052343-2b144e78-35a9-4207-8728-a3f92d43ab75.png)

@mbtools Did you mean zabapgit or zgit ? Could you pls syncronize filename and content, currently pull fails :) 

P.S. If you ask me, I'd vote for a shorter name ...

**Comment by mbtools** [comment]
It can't be `zabapgit` since that's in the dev version. I fixed the filename

**Comment by sbcgua** [comment]
:+1: thanks !
